#! /usr/bin/env bats
#
# These scripts exist to provide help documentation and a uniform means of
# listing all builtin commands via a glob (to aid with 'go help builtins' and
# tab completion), but should never be executed, as their corresponding commands
# are implemented in the @go and environment functions.
#
# Though these scripts should never get executed, these tests ensure they fail
# loudly in case something goes wrong and they are.

load environment
load assertions

setup() {
  declare -g TEST_GO_SCRIPT="$BATS_TMPDIR/go"
  echo . "$_GO_ROOTDIR/go-core.bash" '.' >>"$TEST_GO_SCRIPT"
}

@test "builtins: 'edit' script should exit with an error" {
  local expected="ERROR: \"$TEST_GO_SCRIPT edit\" "
  expected+='is implemented directly within the @go function.'

  echo "_@go.source_builtin 'edit'" >>"$TEST_GO_SCRIPT"
  run "$BASH" "$TEST_GO_SCRIPT"
  assert_failure "$expected"
}

@test "builtins: 'run' script should exit with an error" {
  local expected="ERROR: \"$TEST_GO_SCRIPT run\" "
  expected+='is implemented directly within the @go function.'

  echo "_@go.source_builtin 'run'" >>"$TEST_GO_SCRIPT"
  run "$BASH" "$TEST_GO_SCRIPT"
  assert_failure "$expected"
}

@test "builtins: 'unenv' script should exit with an error" {
  local expected="ERROR: \"$TEST_GO_SCRIPT unenv\" "
  expected+='is implemented in the function generated by '
  expected+="\"$TEST_GO_SCRIPT env\"."

  echo "_@go.source_builtin 'unenv'" >>"$TEST_GO_SCRIPT"
  run "$BASH" "$TEST_GO_SCRIPT"
  assert_failure "$expected"
}

teardown() {
  rm "$TEST_GO_SCRIPT"
}
