#! /bin/bash
#
# Common setup for all tests

. "$_GO_ROOTDIR/lib/bats/helpers"
set_bats_test_suite_name "${BASH_SOURCE[0]%/*}"

# Avoid having to fold our test strings. Tests that verify folding behavior will
# override this.
COLUMNS=1000

# Many tests assume the output is generated by running the script directly, so
# we clear the _GO_CMD variable in case the test suite was invoked using a shell
# function.
unset -v _GO_CMD
