#! /bin/bash
#
# Prefixes <file-paths> with <project-root> or prints <project-root>

if [[ $# -eq 0 ]]; then
  echo "$_GO_ROOTDIR"
fi

for fp in "$@"; do
  if [[ ${fp:0:1} != / ]]; then
    echo "$_GO_ROOTDIR/$fp"
  else
    echo "$fp"
  fi
done
