#! /bin/bash
#
# Prints the path to the <command> script, [alias] or [builtin]

_@go.path() {
  if [[ "$#" -ne '0' ]]; then
    if _@go.source_builtin 'aliases' --exists "$1"; then
      echo '[alias]'
      return
    elif _@go.source_builtin 'builtins' --exists "$1"; then
      echo -n '[builtin] '
    fi

    local __go_cmd_path

    if _@go.set_command_path_and_argv "$@"; then
      echo "${__go_cmd_path#$_GO_ROOTDIR/}"
    else
      return 1
    fi
  fi
}

_@go.path "$@"
