#! /bin/bash
#
# Lists all installed plugin commands
#
# Usage: {{go}} {{cmd}} [--paths|--summaries]
#
# Options:
#   --paths      List all plugin command paths relative to the project root
#   --summaries  List all plugin command summaries
#
# To install plugins, first create a subdirectory of your scripts directory
# called "plugins". Then add any third-party scripts to this new directory.
#
# As with your project-specific scripts, any scripts in this directory must be
# executable and the first line must be of the form: '#!/path/to/interpreter'
#
# Plugins that are installed as directories (possibly as git submodules) should
# contain a `bin/` subdirectory containing its command scripts.

_@go.plugins_pathspec() {
  if [[ -z "$_GO_PLUGINS_DIR" ]]; then
    return 1
  fi

  local plugins_paths=("$_GO_PLUGINS_DIR" "$_GO_PLUGINS_DIR"/*/bin)

  if [[ "${plugins_paths[1]}" == "$_GO_PLUGINS_DIR/*/bin" ]]; then
    unset 'plugins_paths[1]'
  fi

  local IFS=':'
  __go_plugins_pathspec="${plugins_paths[*]}"
}

_@go.plugins() {
  local __go_plugins_pathspec

  if _@go.plugins_pathspec; then
    # Tab completions
    _@go.source_builtin 'commands' "$@" "$__go_plugins_pathspec"
  else
    return 1
  fi
}

_@go.plugins "$@"
