#! /bin/bash
#
# Run automated tests
#
# Usage:
#   {{go}} {{cmd}} [--list]
#   {{go}} {{cmd}} [--list] <glob> [<glob>...]
#
# Without arguments, runs all tests. With one or more <glob> arguments, only
# runs tests matching 'tests/<glob>.bats'. With the --list flag, only lists the
# test file names without executing them.
#
# If a <glob> doesn't match any test files, the command will return an error
# without running any tests. See `{{go}} help glob` for details.
#
# NOTE: If the <glob> produces errors, or generally doesn't do as you expect,
# you may need to include it in quotes so it isn't expanded by the shell
# _before_ executing the {{cmd}} command.

declare -r __go_glob_args=('--ignore' 'bats/*' 'tests' '.bats')

_test_tab_completion() {
  local word_index="$1"
  shift
  if [[ "$word_index" -eq '0' ]]; then
    if [[ -z "$1" ]]; then
      echo '--list'
    elif [[ "${1:0:1}" = '-' ]]; then
      echo '--list'
      return
    fi
  fi
  @go 'glob' '--complete' "$((word_index + ${#__go_glob_args[@]}))" \
    "${__go_glob_args[@]}" "$@"
}

_test() {
  if [[ "$1" = '--complete' ]]; then
    # Tab completions
    shift
    _test_tab_completion "$@"
  elif [[ "$1" = '--list' ]]; then
    shift
    @go 'glob' '--compact' "${__go_glob_args[@]}" "$@"
  else
    local tests=($(@go 'glob' "${__go_glob_args[@]}" "$@"))
    tests/bats/bin/bats "${tests[@]}"
  fi
}

_test "$@"
