#! /bin/bash
#
# Parent command for subcommands

function parent() {
  # Tab completions
  if [[ "$1" = '--complete' ]]; then
    echo one two three
    exit
  fi

  echo "Parent command"
}

parent "$@"
